# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Fenolite contributors
"""Parser: accepted forms, byte offsets, fragments and located rejections (capability kicad-sexpr)."""

from __future__ import annotations

from pathlib import Path

import pytest

from fenolite.backends.kicad import (
    MAX_DEPTH,
    Atom,
    AtomKind,
    Node,
    dumps,
    load,
    parse,
    parse_bytes,
    parse_fragment,
)
from fenolite.core.errors import FormatError

# --- accepted forms -------------------------------------------------------------------------------


def test_accept_numeric_head() -> None:
    root = parse('(layers (0 "F.Cu" signal) (2 "B.Cu" signal))')
    heads = [n.head for n in root.nodes()]
    assert heads == [Atom("0", AtomKind.NUMBER), Atom("2", AtomKind.NUMBER)]
    assert [n.name for n in root.nodes()] == ["0", "2"]


def test_accept_crlf_file() -> None:
    text = '(kicad_pcb\n\t(version 20260206)\n\t(generator "x")\n)\n'
    assert parse(text.replace("\n", "\r\n")) == parse(text)


def test_accept_parentheses_inside_strings() -> None:
    node = parse('(descr "Resistor (THT)")')
    assert len(node.children) == 1 and node.atoms()[0].value == "Resistor (THT)"


def test_accept_raw_control_character_inside_a_string() -> None:
    node = parse('(t "a\x0bb")')
    assert "\x0b" in node.atoms()[0].value


def test_accept_comment_before_the_root() -> None:
    root = parse("# generated by hand\n(kicad_pcb (version 20260206))")
    assert root.comments == ("# generated by hand",)
    assert dumps(root).startswith("# generated by hand\n(kicad_pcb")


def test_accept_several_comment_lines_and_blanks() -> None:
    root = parse("\n  # one\r\n# two\n\n(a 1)\n")
    assert root.comments == ("  # one", "# two")


def test_accept_legacy_unquoted_atoms() -> None:
    root = parse("(module Resistors_SMD:R_0603 (layer F.Cu) (net 1 /VCC))")
    assert root.atoms()[0] == Atom.symbol("Resistors_SMD:R_0603")
    layer, net = root.nodes()
    assert layer.atoms()[0] == Atom.symbol("F.Cu") and net.atoms()[1] == Atom.symbol("/VCC")


def test_accept_quote_inside_unquoted_atom_and_hash_atoms() -> None:
    root = parse('(a b"c #PWR ( page_layout ))')
    assert root.atoms()[0].text == 'b"c' and root.atoms()[1].text == "#PWR"
    assert root.nodes()[0].name == "page_layout"


def test_accept_tree_helpers() -> None:
    root = parse('(fp (at 1 2) (pad "1") (pad "2") x)')
    assert root.find("pad") == root.nodes("pad")[0]
    assert root.find("nope") is None
    assert [a.text for a in root.atoms()] == ["x"]
    assert len(root.nodes()) == 3
    assert root.with_children([]).children == ()
    assert Node(Atom.symbol("a"), [Atom.symbol("b")]).children == (Atom.symbol("b"),)  # type: ignore[arg-type]


def test_offsets_ignored_by_equality() -> None:
    a, b = parse("(a (b 1))"), parse("(a\n\t(b 1)\n)")
    assert a == b
    assert a.nodes()[0].offset != b.nodes()[0].offset


def test_offsets_count_bytes() -> None:
    text = '(a "é" (b))'
    assert parse(text).nodes()[0].offset == 8
    assert parse_bytes(text.encode("utf-8")).nodes()[0].offset == 8
    assert parse("(a (b))").nodes()[0].offset == 3


def test_offsets_after_several_multibyte_characters() -> None:
    text = '(a "日本" (b "ü") (c))'
    expected = [len(text[: text.index("(b")].encode()), len(text[: text.index("(c")].encode())]
    assert [n.offset for n in parse(text).nodes()] == expected


def test_load(tmp_path: Path) -> None:
    path = tmp_path / "x.kicad_pcb"
    path.write_bytes(b"(kicad_pcb (version 20260206))\n")
    assert load(path).name == "kicad_pcb"
    path.write_bytes(b'(kicad_pcb (title "a\nb"))')
    with pytest.raises(FormatError) as info:
        load(path)
    assert info.value.file == str(path)


# --- fragments ------------------------------------------------------------------------------------


def test_fragment_bare_symbol() -> None:
    assert parse_fragment("locked") == Atom("locked", AtomKind.SYMBOL)


def test_fragment_string() -> None:
    atom = parse_fragment('"a b"')
    assert isinstance(atom, Atom) and atom.kind == AtomKind.STRING and atom.value == "a b"


def test_fragment_list_and_whitespace() -> None:
    assert parse_fragment("  (stroke (width 0.1))\n") == parse("(stroke (width 0.1))")
    assert parse_fragment(" 1.5 ") == Atom("1.5", AtomKind.NUMBER)
    assert parse_fragment("#PWR") == Atom.symbol("#PWR")


@pytest.mark.parametrize(
    ("text", "rule"),
    [
        ("a b", "more than one element"),
        ("(a) (b)", "more than one element"),
        ("(a) b", "more than one element"),
        ("", "empty fragment"),
        ("   ", "empty fragment"),
        ("# x\n(a)", "more than one element"),
        (")", "unexpected"),
        ('"a\nb"', "newline inside string"),
        ('"a"b', "atom directly after a closing quote"),
        ("(a", "unbalanced"),
        ("()", "empty list"),
    ],
)
def test_fragment_rejections(text: str, rule: str) -> None:
    with pytest.raises(FormatError, match=rule):
        parse_fragment(text)


# --- rejections -----------------------------------------------------------------------------------


def _reject(text: str, rule: str, *, offset: int | None = None, locator: str | None = None) -> FormatError:
    with pytest.raises(FormatError) as info:
        parse(text, file="x.kicad_pcb")
    error = info.value
    assert rule in str(error), str(error)
    assert error.file == "x.kicad_pcb"
    if offset is not None:
        assert error.offset == offset
    if locator is not None:
        assert error.locator == locator
    return error


def test_reject_raw_newline_in_a_string() -> None:
    text = '(kicad_pcb (title "a\nb"))'
    _reject(text, "newline inside string", offset=text.index("\n"), locator="/kicad_pcb/title[0]")


def test_reject_newline_after_backslash() -> None:
    text = '(a (b "x\\\ny"))'
    _reject(text, "newline inside string", offset=text.index("\n"), locator="/a/b[0]")


def test_reject_byte_order_mark() -> None:
    with pytest.raises(FormatError, match="byte-order mark") as info:
        parse_bytes(b"\xef\xbb\xbf(kicad_pcb (version 20260206))")
    assert info.value.offset == 0
    _reject("﻿(kicad_pcb)", "byte-order mark", offset=0)


def test_reject_trailing_content() -> None:
    text = "(kicad_pcb (version 20260206)) (extra)"
    _reject(text, "content after the root list", offset=text.index("(extra)"))


def test_reject_atom_glued_after_a_multibyte_string() -> None:
    text = '(a "é" "x"y)'
    _reject(text, "atom directly after a closing quote", offset=11, locator="/a")
    with pytest.raises(FormatError) as info:
        parse_bytes(text.encode("utf-8"))
    assert info.value.offset == 11


def test_reject_string_glued_to_string() -> None:
    _reject('(a "x""y")', "atom directly after a closing quote", offset=6)


def test_reject_unbalanced() -> None:
    text = "(kicad_pcb (version 20260206)"
    _reject(text, "unbalanced", locator="/kicad_pcb", offset=len(text))


@pytest.mark.parametrize("text", ["", "   \n\t", "# only a comment\n", "# a\n# b"])
def test_reject_empty(text: str) -> None:
    _reject(text, "empty input")


@pytest.mark.parametrize("text", ["x (a)", ")(a)", '"s" (a)'])
def test_reject_content_before_the_root(text: str) -> None:
    _reject(text, "content before the root list", offset=0)


def test_reject_empty_list() -> None:
    text = "(kicad_pcb (a ()))"
    _reject(text, "empty list ()", offset=text.index("()"), locator="/kicad_pcb/a[0]")


def test_reject_list_starting_with_a_list() -> None:
    text = "(kicad_pcb (b 1) ((c)))"
    _reject(text, "list starting with a list", offset=text.index("((") + 1, locator="/kicad_pcb")
    _reject("((a))", "list starting with a list", offset=1, locator="")


def test_reject_raw_carriage_return_in_a_string() -> None:
    text = '(a (b "x\ry"))'
    _reject(text, "carriage return inside string", offset=text.index("\r"), locator="/a/b[0]")


def test_reject_unterminated_string() -> None:
    text = '(a (b "xyz'
    _reject(text, "unterminated string", offset=text.index('"'), locator="/a/b[0]")


def test_reject_depth_bomb() -> None:
    text = "(a " * 10_000 + ")" * 10_000
    error = _reject(text, "MAX_DEPTH", offset=3 * MAX_DEPTH)
    assert error.locator.count("/") == MAX_DEPTH


def test_depth_at_the_limit_is_accepted() -> None:
    text = "(a " * MAX_DEPTH + ")" * MAX_DEPTH
    assert parse(text).name == "a"


def test_reject_invalid_utf8() -> None:
    data = b'(a "\xc3\xa9" "\xff")'
    with pytest.raises(FormatError, match="invalid UTF-8") as info:
        parse_bytes(data, file="bad.kicad_pcb")
    assert info.value.offset == data.index(b"\xff") and info.value.file == "bad.kicad_pcb"


def test_locator_counts_siblings_with_the_same_head() -> None:
    text = '(kicad_pcb (footprint "a") (net 1) (footprint "b" (pad "1" (at 0 0) (size "x\ny"))))'
    _reject(text, "newline inside string", locator="/kicad_pcb/footprint[1]/pad[0]/size[0]")
