{ Fenolite, Altium verification kit: the kit script.                         }
{ Generated by "fenolite kit build" from the kit's steps; authored for       }
{ Fenolite (Apache-2.0). It writes only under the kit's folder results.      }
{ Use: open a sample project of the kit, focus it, then File, Run Script and }
{ choose FenoliteKitRun. Run it once for each sample project.                }
{ The names and signatures of its calls were read from a text rendering of  }
{ the pages of Altium's public documentation on 2026-10-06, not from the    }
{ pages themselves, and the script has not run in Altium. Before the first  }
{ use: open it in the script editor and compile it; if a line is refused,   }
{ report that line and do the scripted steps by hand.                       }
{ No page that was read states the version of Altium Designer it describes; }
{ the first run of this script is on Altium Designer 26.                    }

Function KitRoot(ProjectPath);
Var
    I, Seen;
Begin
    Result := '';
    I := Length(ProjectPath);
    Seen := 0;
    While (I > 0) And (Seen < 2) Do
    Begin
        If Copy(ProjectPath, I, 1) = '\' Then Seen := Seen + 1;
        If Seen < 2 Then I := I - 1;
    End;
    If Seen = 2 Then Result := Copy(ProjectPath, 1, I);
End;

Procedure LogLine(Root, Line);
Var
    F;
Begin
    AssignFile(F, Root + 'results\script.log');
    Try
        Append(F);
    Except
        Rewrite(F);
    End;
    Writeln(F, Line);
    CloseFile(F);
End;

Procedure CompileAndExport(Project, Root, Sample, StepId);
Var
    Manager, Item, F, I;
Begin
    Try
        Manager := GetWorkspace.DM_MessagesManager;
        Manager.ClearMessages;
        Project.DM_Compile;
        AssignFile(F, Root + 'results\' + Sample + '\messages.txt');
        Rewrite(F);
        I := 0;
        While I < Manager.MessagesCount Do
        Begin
            Item := Manager.Messages(I);
            Writeln(F, '[' + Item.MsgClass + '] ' + Item.Text + ' (' + Item.Source + ')');
            I := I + 1;
        End;
        Writeln(F, 'end of messages');
        CloseFile(F);
        LogLine(Root, StepId + ' done');
    Except
        LogLine(Root, StepId + ' error: the project was not compiled or its messages were not written');
    End;
End;

Procedure FenoliteKitRun;
Var
    Project, Name, Root;
Begin
    Project := GetWorkspace.DM_FocusedProject;
    If Not (Project = Nil) Then
    Begin
        Name := UpperCase(Project.DM_ProjectFileName);
        Root := KitRoot(Project.DM_ProjectFullPath);
        { K2.1 }
        If Name = 'FLAT.PRJPCB' Then CompileAndExport(Project, Root, 'flat', 'K2.1');
        { K2.2 }
        If Name = 'TREE.PRJPCB' Then CompileAndExport(Project, Root, 'tree', 'K2.2');
        { K2.3 }
        If Name = 'ROUTED.PRJPCB' Then CompileAndExport(Project, Root, 'routed', 'K2.3');
        { K2.4 }
        If Name = 'BOARD6.PRJPCB' Then CompileAndExport(Project, Root, 'board6', 'K2.4');
        { K2.5 }
        If Name = 'LIBS.PRJPCB' Then CompileAndExport(Project, Root, 'libs', 'K2.5');
    End;
End;
