# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Fenolite contributors
"""Generate the parts of the agent guide that are lists (capability agent-guide, "Generated guide pages").

    uv run python tools/gen_agent_guide.py          # (re)write the generated files
    uv run python tools/gen_agent_guide.py --check  # exit 1 and name each file that would change

Three files of ``src/fenolite/agent/skill/`` are written from the code that defines their content:

- ``references/commands.md``: every public command with its arguments, from ``fenolite.cli.describe``;
- ``references/dsl-reference.md``: every taught name of ``fenolite.dsl.__all__`` with its signature;
- ``SKILL.md``: the index of the pages, between its two marker lines. The rest of that file is
  written by hand and is not touched.
"""

from __future__ import annotations

import argparse
import inspect
import re
import sys
from collections.abc import Mapping
from pathlib import Path
from types import ModuleType

from fenolite.agent import guide
from fenolite.cli.api import Command, discover
from fenolite.cli.describe import Argument, describe

ROOT = Path(__file__).resolve().parents[1]
SKILL = ROOT / "src" / "fenolite" / "agent" / "skill"
TOOL = "tools/gen_agent_guide.py"
COMMANDS = "references/commands.md"
DSL = "references/dsl-reference.md"
START = "SKILL.md"
NOTE = f"This page is generated by `{TOOL}`: do not edit it, change the code and run the tool."
FRONT = {
    COMMANDS: (
        "commands",
        "Every command and its arguments",
        "The complete list: each public command, whether it writes, and every argument with its help.",
    ),
    DSL: (
        "dsl-reference",
        "The names of the design script",
        "The complete list: each name a design script imports from fenolite.dsl, with its signature.",
    ),
}
"""Published path → the topic, title and summary of a generated page."""
_REFERENCE = re.compile(r"\s*\((?:``docs/|capability |change c\d)[^()]*\)")
_CHANGE = re.compile(r"[;,]? ?\bchanges? c\d{4}(?:(?:, | and )c\d{4})*")
_ADDRESS = re.compile(r" at 0x[0-9a-fA-F]+")


def _front(path: str) -> str:
    topic, title, summary = FRONT[path]
    return f"---\ntopic: {topic}\ntitle: {title}\nsummary: {summary}\n---\n\n# {title}\n\n{NOTE}\n"


def _cell(text: str) -> str:
    """``text`` as one table cell or list item: one line, no pipe that would end the cell."""
    return " ".join(text.split()).replace("|", "\\|")


def _argument(argument: Argument) -> str:
    name = ", ".join(f"`{flag}`" for flag in argument.flags) or f"`{argument.name.upper()}`"
    facts = [argument.type]
    if argument.choices:
        facts.append("one of " + ", ".join(f"`{choice}`" for choice in argument.choices))
    if argument.kind == "positional":
        facts.append("required" if argument.required else "optional")
    elif argument.required:
        facts.append("required")
    if argument.repeatable:
        facts.append("repeatable")
    if argument.default not in (None, False, [], ()):
        facts.append(f"default `{argument.default}`")
    line = f"- {name} ({', '.join(facts)})"
    return f"{line}: {_cell(argument.help)}" if argument.help else line


def commands_page(registry: Mapping[str, Command]) -> str:
    """The page ``commands``: the public commands of ``registry`` in name order."""
    public = [registry[name] for name in sorted(registry) if not registry[name].hidden]
    described = [describe(command) for command in public]
    lines = [
        _front(COMMANDS),
        "A command that writes does nothing without `--dry-run` (show the plan) or `--confirm` (write).",
        "`fenolite capabilities --command NAME --json` gives the same facts as data.",
        "",
        "| command | writes | summary |",
        "|---|---|---|",
    ]
    lines += [
        f"| `{entry.name}` | {'yes' if entry.mutates else 'no'} | {_cell(entry.summary)} |"
        for entry in described
    ]
    for entry in described:
        lines += ["", f"## {entry.name}", "", f"`{_cell(entry.usage)}`", ""]
        lines += [_argument(argument) for argument in entry.arguments] or ["It takes no argument of its own."]
    return "\n".join(lines) + "\n"


def _sentence(obj: object) -> str:
    """The first sentence of the docstring of ``obj``, without references to the repository."""
    text = " ".join((inspect.getdoc(obj) or "").split())
    text = _CHANGE.sub("", _REFERENCE.sub("", text)).replace("``", "`")
    end = re.search(r"\.(?= [A-Z`]|$)", text)
    return text[: end.end()] if end else text


def _signature(obj: object) -> str:
    try:
        return _ADDRESS.sub("", str(inspect.signature(obj)))  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return ""


def _kind(obj: object) -> str:
    if inspect.isclass(obj):
        return "class"
    if inspect.isroutine(obj):
        return "function"
    return "module" if isinstance(obj, ModuleType) else "constant"


def _entry(name: str, obj: object, level: str) -> list[str]:
    kind = _kind(obj)
    lines = ["", f"{level} {name}", ""]
    if kind in ("class", "function"):
        lines.append(f"{kind.capitalize()}: `{_cell(name + _signature(obj))}`")
    else:
        lines.append(f"{kind.capitalize()}.")
    sentence = _sentence(obj) if kind != "constant" else ""
    if sentence:
        lines += ["", sentence]
    return lines


def dsl_page(namespace: ModuleType, not_taught: Mapping[str, str]) -> str:
    """The page ``dsl-reference``: the names of ``namespace.__all__`` that are not in ``not_taught``."""
    lines = [
        _front(DSL),
        "Every name is imported from `fenolite.dsl`. The methods of a class (`Design.board`, `Part.place`,",
        "`Design.track` and the others) are taught by the written pages; `docs/dsl.md` of the source",
        "repository is the full reference.",
    ]
    for name in sorted(namespace.__all__):
        if name in not_taught:
            continue
        obj = getattr(namespace, name)
        lines += _entry(name, obj, "##")
        if isinstance(obj, ModuleType):
            for member in sorted(getattr(obj, "__all__", ())):
                inner = getattr(obj, member)
                if inspect.isroutine(inner) or inspect.isclass(inner):
                    lines += _entry(f"{name}.{member}", inner, "###")
    return "\n".join(lines) + "\n"


def index(skill: Path, generated: Mapping[str, str]) -> list[str]:
    """One line per page other than the start page, in topic order: the topic and its summary."""
    found: dict[str, str] = {}
    folder = skill / "references"
    texts = {path.name: path.read_text(encoding="utf-8") for path in sorted(folder.glob("*.md"))}
    texts.update({Path(path).name: text for path, text in generated.items()})
    for name, text in texts.items():
        front, _ = guide.front_matter(text.replace("\r\n", "\n"), f"references/{name}", guide.PAGE_KEYS)
        found[front["topic"]] = front["summary"]
    return [f"- `{topic}`: {found[topic]}" for topic in sorted(found)]


def start_page(text: str, lines: list[str]) -> str:
    """``text`` (the start page) with ``lines`` between its two marker lines."""
    rows = text.split("\n")
    if rows.count(guide.PAGES_BEGIN) != 1 or rows.count(guide.PAGES_END) != 1:
        raise guide.GuideError(
            f"{START}: expected one {guide.PAGES_BEGIN} line and one {guide.PAGES_END} line"
        )
    begin, end = rows.index(guide.PAGES_BEGIN), rows.index(guide.PAGES_END)
    if end < begin:
        raise guide.GuideError(f"{START}: {guide.PAGES_END} comes before {guide.PAGES_BEGIN}")
    return "\n".join([*rows[: begin + 1], *lines, *rows[end:]])


def render(skill: Path = SKILL, registry: Mapping[str, Command] | None = None) -> dict[str, str]:
    """Published path (relative to the skill folder) → the text the tool writes there."""
    import fenolite.dsl

    pages = {
        COMMANDS: commands_page(discover() if registry is None else registry),
        DSL: dsl_page(fenolite.dsl, guide.DSL_NOT_TAUGHT),
    }
    start = (skill / START).read_text(encoding="utf-8")
    return {**pages, START: start_page(start, index(skill, pages))}


def stale(skill: Path = SKILL, registry: Mapping[str, Command] | None = None) -> list[str]:
    """The published paths whose file is missing or differs from what the tool writes."""
    found: list[str] = []
    for path, text in render(skill, registry).items():
        target = skill / path
        if not target.is_file() or target.read_text(encoding="utf-8") != text:
            found.append(path)
    return found


def main(
    argv: list[str] | None = None, *, skill: Path = SKILL, registry: Mapping[str, Command] | None = None
) -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    parser.add_argument("--check", action="store_true", help="write nothing; exit 1 if a file would change")
    args = parser.parse_args(argv)
    if args.check:
        changed = stale(skill, registry)
        if changed:
            print(f"stale guide files (run {TOOL}):\n  " + "\n  ".join(changed), file=sys.stderr)
            return 1
        return 0
    for path, text in render(skill, registry).items():
        target = skill / path
        if target.is_file() and target.read_text(encoding="utf-8") == text:
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
