# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Fenolite contributors
"""Render docs/evidence/matrix.md from the evidence declarations of the backends and the register.

    uv run python tools/gen_evidence_matrix.py [--check]

``--check`` writes nothing and exits 1 when the committed page differs from a fresh rendering. The page
is a function of the working tree only: no date, no tool version and no absolute path (capability
verification-evidence, "Generated evidence matrix page"; change c0067).
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Sequence
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT / "src") not in sys.path:
    sys.path.insert(0, str(ROOT / "src"))

from fenolite.backends import matrix  # noqa: E402
from fenolite.backends.base import MATRIX_OPERATIONS, MatrixRow  # noqa: E402
from fenolite.core.evidence import Evidence  # noqa: E402
from fenolite.verify import HypothesisRow, load_register  # noqa: E402

PAGE = ROOT / "docs" / "evidence" / "matrix.md"
REGISTER = ROOT / "docs" / "hypotheses.md"
PAGE_NAME = "docs/evidence/matrix.md"
TOOL_NAME = "tools/gen_evidence_matrix.py"
COMMAND = f"uv run python {TOOL_NAME}"
NOT_SET = "—"
MEANINGS = (
    ("detect", "the package names the kind of a file from its name or its content"),
    ("read", "a reader of the package builds a model object from a file of the kind"),
    (
        "write",
        "a writer of the package produces a file of the kind from a model object that Fenolite created",
    ),
    (
        "roundtrip_exact",
        "a file of the kind that is read and written back for the same version, with no change in between, "
        "keeps its whole content, modelled or not",
    ),
    (
        "roundtrip_modified",
        "a file of the kind that is read, changed through the model and written keeps everything the "
        "change did not touch, or the write is refused",
    ),
)


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def _line(cells: Sequence[str]) -> str:
    return "| " + " | ".join(_cell(cell) for cell in cells) + " |"


def _operation(row: MatrixRow, operation: str) -> str:
    cell: Evidence | None = getattr(row, operation)
    if cell is None:
        return NOT_SET
    return cell.label() + (" (experimental)" if operation in row.experimental else "")


def _ids(idents: Sequence[str]) -> str:
    return ", ".join(f"`{ident}`" for ident in idents) or NOT_SET


def render(
    rows: Sequence[MatrixRow] | None = None,
    claims: Sequence[matrix.ModuleClaim] | None = None,
    register: Sequence[HypothesisRow] | None = None,
) -> str:
    """The page text. With no argument it is rendered from the working tree: ``matrix.rows()``, the
    ``module_claims`` of every backend package and ``docs/hypotheses.md``."""
    if rows is None:
        rows = matrix.rows()
    if claims is None:
        claims = [claim for package in matrix.packages() for claim in matrix.module_claims(package)]
    if register is None:
        register = load_register(REGISTER)
    by_id = {row.id: row for row in register}
    lines = [
        "# Evidence matrix",
        "",
        f"Generated by `{TOOL_NAME}` from the evidence declarations of the modules under",
        "`src/fenolite/backends/` (`fenolite.backends.matrix`) and from `docs/hypotheses.md`. Do not edit by",
        f"hand: change a declaration or a register row and run `{COMMAND}`.",
        "`tests/unit/test_evidence_matrix_page.py` fails while this page is stale. `fenolite capabilities`",
        "lists the same rows as `result.matrix`.",
        "",
        "## Operations",
        "",
        "A row states what one backend package does with one file kind, and how well each operation is",
        "verified. A label states what holds for an arbitrary file of the kind, so it is often weaker than",
        "the rows it names: a row of the register states what its test covered. A label is never stronger",
        "than a row it names (lowest wins).",
        "",
        "| operation | meaning |",
        "|---|---|",
        *(_line([f"`{name}`", meaning]) for name, meaning in MEANINGS),
        "",
        f"`{NOT_SET}` means that the package does not implement the operation for the kind. `(experimental)`",
        "marks an operation that may change its output, its options or its issue codes in any release.",
        "",
        "## Matrix",
        "",
        _line(["backend", "kind", *MATRIX_OPERATIONS, "verified_by"]),
        "|---|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        cells = [_operation(row, operation) for operation in MATRIX_OPERATIONS]
        lines.append(_line([row.backend, f"`{row.kind}`", *cells, _ids(row.verified_by())]))
    named = sorted({ident for row in rows for ident in row.verified_by()})
    lines += [
        "",
        "## Hypotheses",
        "",
        "The level that `docs/hypotheses.md` holds for each id a row names, as written there. The statement,",
        "the settling test and the result of an id are in its register row.",
        "",
        "| id | level in the register |",
        "|---|---|",
    ]
    for ident in named:
        found = by_id.get(ident)
        level = (
            "not registered" if found is None else found.level_text + (" (refuted)" if found.refuted else "")
        )
        lines.append(_line([f"`{ident}`", level]))
    lines += [
        "",
        "## Modules",
        "",
        "Every module of a backend package declares its evidence in one of three forms: constants (it owns",
        "a claim), `see` (its code runs only inside the operations of the named modules of the package), or",
        "`none` with a reason (it states nothing about a file format or a tool).",
    ]
    for package in sorted({claim.package for claim in claims}):
        lines += ["", f"### `{package}`", "", "| module | declaration |", "|---|---|"]
        for claim in sorted((c for c in claims if c.package == package), key=lambda c: c.module):
            if claim.constants:
                parts = [
                    f"`{name}` {evidence.label()}: {_ids(evidence.hypotheses)}"
                    for name, evidence in claim.constants
                ]
                declared = "<br>".join(parts)
            elif claim.see:
                declared = "see " + ", ".join(f"`{name}`" for name in claim.see)
            else:
                declared = f"none: {claim.none}"
            lines.append(_line([f"`{claim.module}`", declared]))
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=f"Render {PAGE_NAME}.")
    parser.add_argument("--check", action="store_true", help="exit 1 when the committed page is out of date")
    parser.add_argument("--page", type=Path, default=PAGE)
    args = parser.parse_args(argv)
    text = render()
    if args.check:
        current = args.page.read_bytes().decode("utf-8") if args.page.is_file() else ""
        if current != text:
            print(f"{PAGE_NAME} is out of date: run '{COMMAND}' and commit the page", file=sys.stderr)
            return 1
        return 0
    args.page.write_bytes(text.encode("utf-8"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
