# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Fenolite contributors
"""Render docs/formats/kicad/tokens.md from the token inventory and the committed fuzz results.

    uv run python tools/gen_token_docs.py [--check]

``--check`` exits 1 when the committed page differs from a fresh rendering.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path
from types import ModuleType
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT / "src") not in sys.path:
    sys.path.insert(0, str(ROOT / "src"))

from fenolite.backends.kicad.versions import Inventory, load_inventory  # noqa: E402

PAGE = ROOT / "docs" / "formats" / "kicad" / "tokens.md"
RESULTS = ROOT / "docs" / "evidence" / "kicad" / "token-fuzz"
MAJORS = (9, 10)


def _fuzz() -> ModuleType:
    name = "fenolite_kicad_token_fuzz"
    if name in sys.modules:
        return sys.modules[name]
    spec = importlib.util.spec_from_file_location(name, ROOT / "tools" / "kicad_token_fuzz.py")
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def _results(directory: Path) -> list[dict[str, Any]]:
    return [json.loads(p.read_text(encoding="utf-8")) for p in sorted(directory.glob("*.json"))]


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def render(inventory: Inventory, results: list[dict[str, Any]]) -> str:
    levels = _fuzz().row_levels(inventory, results)
    versions = sorted(str(r["kicad_cli"]["version"]) for r in results)
    lines = [
        "# KiCad token inventory",
        "",
        "Generated by `tools/gen_token_docs.py` from `src/fenolite/backends/kicad/data/tokens.toml` and",
        f"`docs/evidence/kicad/token-fuzz/` (results for kicad-cli {', '.join(versions) or 'none'}).",
        "Do not edit by hand. The rows are authored from public sources; the levels are computed from the",
        "committed fuzz results: `KICAD-VERIFIED` when the major's cases prove the row, else `INFERRED`.",
        "",
        "## Token rows",
        "",
        "| id | kinds | path | value | since | until | sources | hypothesis | 9.0 | 10.0 |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for row in inventory.tokens:
        since = f"{row.since_major}" + (f" ({row.since_version})" if row.since_version else "")
        until = "" if row.until_major is None else str(row.until_major)
        kinds = ", ".join(sorted(k.value for k in row.kinds))
        level = [levels[row.id].get(m, "—") for m in MAJORS]
        value = "" if row.value is None else f"`{row.value}`"
        cells = [
            row.id,
            kinds,
            f"`{row.path}`",
            value,
            since,
            until,
            ", ".join(row.sources),
            row.hypothesis or "",
            str(level[0]),
            str(level[1]),
        ]
        lines.append("| " + " | ".join(_cell(c) for c in cells) + " |")
    lines += [
        "",
        "## Form rows",
        "",
        "| id | kinds | applies to | since | description | sources | hypothesis | 9.0 | 10.0 |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for form in inventory.forms:
        since = f"{form.since_major}" + (f" ({form.since_version})" if form.since_version else "")
        kinds = ", ".join(sorted(k.value for k in form.kinds))
        cells = [
            form.id,
            kinds,
            form.applies_to,
            since,
            form.description,
            ", ".join(form.sources),
            form.hypothesis or "",
            str(levels[form.id].get(9, "—")),
            str(levels[form.id].get(10, "—")),
        ]
        lines.append("| " + " | ".join(_cell(c) for c in cells) + " |")
    sections = (
        ("kicad_pcb", "## Dated board-format versions (S-0030)"),
        ("kicad_sch", "## Dated schematic-format versions (S-0031)"),
        ("kicad_sym", "## Dated symbol-library versions (S-0031)"),
    )
    for kind, title in sections:
        notes = [note for note in inventory.notes if note.kind.value == kind]
        if not notes:
            continue
        lines += ["", title, "", "| version | rows or reason |", "|---|---|"]
        for note in notes:
            what = ", ".join(note.rows) if note.rows else f"_{note.no_row}_"
            lines.append(f"| {note.version} | {what} |")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render docs/formats/kicad/tokens.md.")
    parser.add_argument("--check", action="store_true", help="exit 1 when the committed page is out of date")
    parser.add_argument("--results", type=Path, default=RESULTS)
    parser.add_argument("--page", type=Path, default=PAGE)
    args = parser.parse_args(argv)
    text = render(load_inventory(), _results(args.results))
    if args.check:
        current = args.page.read_text(encoding="utf-8") if args.page.is_file() else ""
        if current != text:
            shown = args.page.relative_to(ROOT) if args.page.is_relative_to(ROOT) else args.page
            print(f"{shown} is out of date: run 'uv run python tools/gen_token_docs.py'", file=sys.stderr)
            return 1
        return 0
    args.page.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
