# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Fenolite contributors
"""``fenolite roundtrip PATH``: up to which level Fenolite reads a KiCad file and writes it back without
loss (capability cli-contract, "Roundtrip command"; ``docs/cli-contract.md``, "roundtrip").

RT0 is the parser and the printer; RT1 the backend's same-version rebuild; RT2 the oracle's DRC of the
file and of its re-dump, on copies. An agent runs this before it edits a file Fenolite did not write.
"""

from __future__ import annotations

import argparse
import hashlib
from collections.abc import Mapping
from pathlib import Path
from types import MappingProxyType
from typing import Any

from fenolite.backends import registry
from fenolite.backends.base import Validator
from fenolite.backends.kicad import versions
from fenolite.backends.kicad.oracle import KicadOracle
from fenolite.backends.kicad.projectset import project_set, resolve_board
from fenolite.backends.kicad.sexpr import dumps, first_difference, parse, tree_equal
from fenolite.checks.rt2 import rt2_stage
from fenolite.cli._examples import EXAMPLE_BOARD
from fenolite.cli._kicadtool import DEFAULT_TIMEOUT, preflight
from fenolite.cli.api import Command, Context, Result
from fenolite.cli.errors import CliError
from fenolite.cli.output import InputRef
from fenolite.core.errors import Issue, Severity
from fenolite.core.evidence import Evidence, Level

HELP = "say up to which level (rt0, rt1, rt2) a KiCad file survives a read and a write"
LEVELS = ("rt0", "rt1", "rt2")
KINDS = frozenset(
    {
        versions.FileKind.BOARD,
        versions.FileKind.FOOTPRINT,
        versions.FileKind.SCHEMATIC,
        versions.FileKind.SYMBOL_LIB,
        versions.FileKind.WORKSHEET,
    }
)
TREE_EVIDENCE = Evidence(Level.INFERRED, hypotheses=("H-K-SEXPR-STRICT",))
ISSUE_CODES: Mapping[str, Severity] = MappingProxyType({"roundtrip.failed": "error"})
NOT_APPLICABLE = "not-applicable"
NOT_RUN = "not-run"
NO_TOOL_HINT = "install KiCad 9 or 10, set FENOLITE_KICAD_CLI or pass --kicad-cli, or ask for --level rt1"
READS = "roundtrip reads .kicad_pcb, .kicad_mod, .kicad_sch, .kicad_sym and .kicad_wks"


def _register(parser: argparse.ArgumentParser) -> None:
    parser.description = HELP + "; see docs/cli-contract.md, 'roundtrip'."
    parser.add_argument("path", metavar="PATH", help="a KiCad S-expression file, or a project for rt2")
    parser.add_argument("--level", choices=LEVELS, default="rt1", help="the level to reach (default rt1)")
    parser.add_argument("--kicad-cli", dest="kicad_cli", metavar="PATH", help="the kicad-cli of rt2")
    parser.add_argument(
        "--timeout", type=float, default=DEFAULT_TIMEOUT, metavar="SECONDS", help="kicad-cli timeout (300)"
    )


def _target(given: str, ctx: Context) -> Path:
    path = Path(given)
    path = path if path.is_absolute() else ctx.cwd / path
    if not path.exists():
        raise CliError("FEN-3001", f"{path.name} does not exist", where=path.name)
    if path.is_dir() or path.suffix == ".kicad_pro":
        return resolve_board(path)
    if versions.kind_for_suffix(path.name) not in KINDS:
        raise CliError("FEN-2001", f"roundtrip does not read {path.name}", hint=READS, where=path.name)
    return path


def _rt0(text: str, file: str) -> dict[str, Any]:
    root = parse(text, file=file)
    try:
        again = parse(dumps(root), file=file)
    except ValueError as exc:  # the printer refuses comments below the root
        return {"passed": False, "difference": str(exc)}
    equal = tree_equal(again, root)
    difference = "" if equal else (first_difference(again, root) or f"/{root.name}")
    return {"passed": equal, "difference": difference}


def _failed(level: str, name: str, difference: str) -> Issue:
    return Issue(
        code="roundtrip.failed",
        severity="error",
        message=f"{name} does not survive {level.upper()}",
        where=difference,
        hint="do not edit this file through Fenolite: content would be lost or changed",
    )


def _run(args: argparse.Namespace, ctx: Context) -> Result:
    path = _target(args.path, ctx)
    kind = versions.kind_for_suffix(path.name)
    assert kind is not None
    data = path.read_bytes()
    asked = LEVELS[: LEVELS.index(args.level) + 1]
    oracle = None
    if "rt2" in asked:
        if kind is not versions.FileKind.BOARD:
            raise CliError(
                "FEN-2001", f"rt2 judges the board of a project, and {path.name} is {kind.value}", hint=READS
            )
        oracle = KicadOracle(preflight(args.kicad_cli, args.timeout, path, hint=NO_TOOL_HINT))
    result: dict[str, Any] = {"kind": kind.value, "level": "none"}
    issues: list[Issue] = []
    evidence = TREE_EVIDENCE

    rt0 = _rt0(data.decode("utf-8"), path.name)
    result["rt0"] = rt0
    holds = bool(rt0["passed"])
    if holds:
        result["level"] = "rt0"
    else:
        issues.append(_failed("rt0", path.name, rt0["difference"]))

    if "rt1" in asked:
        backend = registry.for_path(path)
        if not holds:
            result["rt1"] = NOT_RUN
        elif kind is not versions.FileKind.BOARD or not isinstance(backend, Validator):
            result["rt1"] = NOT_APPLICABLE
        else:
            found: list[Issue] = []
            validation = backend.validate(path, issues=found)
            verdict = validation.roundtrip
            issues += found
            evidence = validation.read.evidence
            result["rt1"] = {
                "passed": verdict.passed,
                "difference": verdict.difference,
                "opaque_count": verdict.opaque_count,
            }
            holds = verdict.passed
            if holds:
                result["level"] = "rt1"
            else:
                issues.append(_failed("rt1", path.name, verdict.difference))

    if oracle is not None:
        if not holds or result.get("rt1") == NOT_APPLICABLE:
            result["rt2"] = NOT_RUN
        else:
            stage = rt2_stage(oracle, project_set(path))
            summary = stage.summary
            differences = [i for i in stage.issues if i.code == "check.rt2-failed"]
            judged = bool(summary["judged"])
            passed = judged and bool(summary["holds"])
            result["rt2"] = {
                "passed": passed,
                "difference": differences[0].where or differences[0].message if differences else "",
                "judged": judged,
                "normalised": summary["normalised"],
                "runs": summary["runs"],
                "before": summary["before"],
                "after": summary["after"],
                "unstable": summary["unstable"],
                "differences": summary["differences"],
            }
            issues += [i for i in stage.issues if i.code != "check.rt2-failed"]
            if passed:
                result["level"] = "rt2"
                evidence = Evidence.combine(evidence, stage.evidence)
            elif differences:
                first = differences[0]
                issues.append(_failed("rt2", path.name, first.where or first.message))

    return Result(
        result=result,
        issues=tuple(issues),
        evidence=evidence,
        input=InputRef(
            path=path.name, sha256=hashlib.sha256(data).hexdigest(), kind=kind.value, format_version=None
        ),
    )


COMMAND = Command(
    name="roundtrip",
    help=HELP,
    mutates=False,
    register=_register,
    run=_run,
    example_args=(EXAMPLE_BOARD,),
)
